version: 2

enable-beta-ecosystems: true

updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dart"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "actions"
      - "dependencies"
