name: ⭐ Feature request
assignees:
  - gokadzev
description: Suggest a feature to improve the app
title: "[Feature] <title>"
labels:
  - enhancement

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    attributes:
      label: Category of the Feature
      description: In which category you think your feature belongs to.
      multiple: true
      options:
        - UI Improvements
        - Logical Improvements
        - More Efficiency
        - Performance Improvements
        - UX Improvements
        - Code Refactor
        - Unable to categorize
  - type: input
    attributes:
      label: Credits
      description: Who've contributed to this idea of this feature?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Pain
      description: Explain the pain you're experiencing.
      placeholder: e.g. I don't like that I've to do this...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested Solution
      description: Tell us about your solution
    validations:
      required: true
  - type: textarea
    attributes:
      label: Useful resources/references
      description: Provide us with some useful resources/references which will help us implement your solution.
