on: workflow_dispatch
name: Test, Build and Release debug apk

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Setup Java environment in order to build the Android app.
    - uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: "12.x"


    # Gradle cache for faster builds
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v2
      with:
        channel: "stable"

    # Get flutter dependencies.
    - run: flutter pub get
    # Check for any formatting issues in the code.
    - run: dart format --set-exit-if-changed .
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    # Add updater
    - run: bash add_updater.sh
    # Build universal apk.
    - run: flutter build apk --debug
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_name: gokadzev/Musify
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/app/outputs/flutter-apk/app-debug.apk
        asset_name: Musify-debug.apk
        tag: ${{ github.ref }}
        prerelease: true
        overwrite: true
        body: "**New Musify Debug App!** \n
        with Debug / BETA builds you have access to the latest build of the app. Only use this version if you test the app, provide feedback, and help us improve its performance. Please note that Debug/BETA versions of the app may be pretty unstable. You may experience crashes, bugs, or other issues while using the app..
        "
